#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "wishthis"
name = "Wishthis"
description.en = "wishlist platform to create, manage and view your wishes for any kind of occasion"
description.fr = "plateforme de listes de souhaits pour créer, gérer et visualiser vos souhaits pour tout type d'occasion"

version = "1.1.1~ynh1"

maintainers = ["johndoe"]

[upstream]
license = "AGPL-3.0"
website = "https://wishthis.online/"
demo = "https://wishthis.online/"
code = "https://github.com/wishthis/wishthis"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wishthis"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/wishthis/wishthis/archive/refs/tags/v1.1.1.tar.gz"
        sha256 = "2f1d3a6f40f32461c7378f42af465a9457500feadd0a5c95fafaed664c83d318"

        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-intl"

    [resources.database]
    type = "mysql"
